n1=int(input("Enter N1 value: "))
n2=int(input("Enter N2 value: "))
n3=int(input("Enter N3 value: "))
add=n1+n2+n3
print(f"The addition of 3 Numbers={add}")
# n1=int(input("Enter N1 value: "))
# n2=int(input("Enter N2 value: "))
# n3=int(input("Enter N3 value: "))
# add=n1+n2+n3
# print(f"The addition of 3 Numbers={add}")
# n1=int(input("Enter N1 value: "))
# n2=int(input("Enter N2 value: "))
# n3=int(input("Enter N3 value: "))
# add=n1+n2+n3
# print(f"The addition of 3 Numbers={add}")
# n1=int(input("Enter N1 value: "))
# n2=int(input("Enter N2 value: "))
# n3=int(input("Enter N3 value: "))
# add=n1+n2+n3
# print(f"The addition of 3 Numbers={add}")